remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme

title: [Sean Kosman]
tagline: [Showcasing Sean's GIS career]
description: [Sean Kosman's github site, showcasing his GIS career and projects he is currently working on]
